# -*- coding: utf-8 -*-
"""GoogleDriveLoadData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15RC4Iu7u56xt8Q_6UlMJO2hnpqyqSCe0
"""

# To read data directly from Google Drive rather than downloading and using it locally

# To install PyDrive uncomment below line
# !pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# URL Example: "https://drive.google.com/file/d/1ClBptsK3V5KgKXtK2GSRzFNAW7GnTPDW/view?usp=drivesdk"

class DatasetLoader(object):
  def __init__(self, url=None):
    self.__url = url

    # Authenticate and create the PyDrive client.
    auth.authenticate_user()
    gauth = GoogleAuth()
    gauth.credentials = GoogleCredentials.get_application_default()
    self.__drive = GoogleDrive(gauth)

  def load_data(self, fileName = 'data'):
    file_id = self.__url.split('/')[-2]

    downloaded = self.__drive.CreateFile({'id':file_id}) 
    downloaded.GetContentFile(fileName)

# Example to use

# data = DatasetLoader("https://drive.google.com/file/d/1ClBptsK3V5KgKXtK2GSRzFNAW7GnTPDW/view?usp=drivesdk")
# data.load_data('abc.csv')

# import pandas as pd
# myData = pd.read_csv('abc.csv')
# myData.head()

